package it.h2i.idservice.accountablemodel.model;
// Generated 4-apr-2018 17.24.09 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,catalog="organization"
)
public class Role  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -6682397654860964308L;
	private Integer idrole;
     private Function function;
     private String name;
     private Set<Appertain> appertains = new HashSet<Appertain>(0);

    public Role() {
    }

	
    public Role(String name) {
        this.name = name;
    }
    public Role(Function function, String name, Set<Appertain> appertains) {
       this.function = function;
       this.name = name;
       this.appertains = appertains;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idrole", unique=true, nullable=false)
    public Integer getIdrole() {
        return this.idrole;
    }
    
    public void setIdrole(Integer idrole) {
        this.idrole = idrole;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_idfunction")
    public Function getFunction() {
        return this.function;
    }
    
    public void setFunction(Function function) {
        this.function = function;
    }
    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="role")
    public Set<Appertain> getAppertains() {
        return this.appertains;
    }
    
    public void setAppertains(Set<Appertain> appertains) {
        this.appertains = appertains;
    }




}


