package it.h2i.idservice.accountablemodel.model;
// Generated 4-apr-2018 17.24.09 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Typology generated by hbm2java
 */
@Entity
@Table(name="typology"
    ,catalog="organization"
)
public class Typology  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 7262089044924059510L;
	private Integer idtype;
     private Organization organization;
     private Function function;
     private String name;

    public Typology() {
    }

	
    public Typology(String name) {
        this.name = name;
    }
    public Typology(Organization organization, Function function, String name) {
       this.organization = organization;
       this.function = function;
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idtype", unique=true, nullable=false)
    public Integer getIdtype() {
        return this.idtype;
    }
    
    public void setIdtype(Integer idtype) {
        this.idtype = idtype;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="typology_idorganization")
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="typology_idfunction")
    public Function getFunction() {
        return this.function;
    }
    
    public void setFunction(Function function) {
        this.function = function;
    }
    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


